# Your project's server will run on localhost:xxxx at this port
PORT: 8080

# UnCSS will use these settings
UNCSS_OPTIONS:
  html:
    - "src/**/*.html"
  ignore:
    - !!js/regexp .foundation-mq
    - !!js/regexp ^\.is-.*

# Gulp will reference these paths when it copies files
PATHS:
  # Builde paths (static sites version)
  #================================================
  dist: "dist"
  distAssets: "/assets"
  # Build paths (ee version)
  #================================================
  # dist: "../assets"
  # distAssets: ""
  #================================================
  # rsync paths
  #================================================
  # eeTemplates: "../../publisher/user/templates/reif"
  # eeTemplatesServer: "~/public_html/publisher/user/templates/reif/"
  # distServer: "~/public_html/html/assets/"
  #================================================
  # Paths to static assets that aren't images, CSS, or JavaScript
  sass:
    - "node_modules/foundation-sites/scss"
  # Paths to static assets that aren't images, CSS, or JavaScript
  media:
    - "src/assets/media/**/*"
  # Path to favicons, app icons, xml and mainfest files
  favicons:
    - "src/assets/favicons/**/*"
  # Paths to JavaScript libraries, which are combined into one file
  vendor:
    - "src/assets/js/vendor.js"
  # Paths to Sass libraries, which can then be loaded with @import
  javascript:
  # external js file
    - "src/assets/js/app.js"
  # react entry js file
  react:
    - "src/react-app/app.js"
  manifest:
    - "src/manifest/manifest.json"